# Generated by Django 4.2.7 on 2024-01-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_product_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
