# Generated by Django 4.2.7 on 2024-01-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
